"""
Parsing wrappers and AST iteration helpers.

``parse_string``/``parse_files`` wrap the callback-based ``clingo_funasp.ast``
parser into functions that return a ``list[Statement]`` (each parsed clingo
statement wrapped in a :class:`Statement`) and convert clingo parsing errors
into :class:`~funasp.util.ast.ParsingException` carrying
:class:`~funasp.util.ast.SyntacticError` locations. ``transform_iterable``
applies a transformer across an iterable, preserving unchanged elements.

``ast_to_str`` re-prints an as-parsed (F-encoded) statement in FASP syntax:
the parser desugars assignments into prefixed atoms before the pipeline sees
any text (``f := a+1.`` becomes ``Ff(a+1).``), so for error and info messages
``ast_to_str`` inverts exactly the shapes the parser generates (detected via
the hardcoded ``F``/``FS`` markers, which user-written function names cannot
produce); anything else falls back to ``str()``.
"""

import re
from dataclasses import dataclass, field
from typing import Callable, Iterable, Sequence

from clingo_funasp import ast
from clingo_funasp.core import Library, Location, MessageType, Position

from funasp import core
from funasp.util.ast import ParsingException, SyntacticError

#: The prefix hardcoded in the clingo_funasp parser.
PARSER_PREFIX = "F"

#: The suffix appended to the prefix by the parser for ``#some`` assignments.
SOME_MARKER = "S"

#: The prefix generated by the parser for ``#some`` assignments.
PARSER_SOME_PREFIX = PARSER_PREFIX + SOME_MARKER

# Errors for strings use an angle-bracketed name (`<string>:1:2-3: error: ...`)
# while errors for files use the plain file name (`file.lp:1:2-3: error: ...`).
_PARSING_ERROR_RE = r"(?:<(?P<bracketed>.*?)>|(?P<file>.*?)):(?P<line>\d+):(?P<col_start>\d+)-(?P<col_end>\d+): error: (?P<msg>.*)"
_PARSING_ERROR_PATTERN = re.compile(_PARSING_ERROR_RE)


def _process_error(
    library: Library, message: tuple[MessageType, str]
) -> SyntacticError:
    """Convert a clingo parsing error message tuple into a SyntacticError."""
    match = _PARSING_ERROR_PATTERN.match(message[1])
    if not match:  # pragma: no cover
        position = Position(library, "<unknown>", 0, 0)
        location = Location(position, position)
        msg = message[1]
    else:
        file = match["bracketed"] if match["bracketed"] is not None else match["file"]
        msg = match["msg"]
        start = Position(library, file, int(match["line"]), int(match["col_start"]))
        end = Position(library, file, int(match["line"]), int(match["col_end"]))
        location = Location(start, end)
    return SyntacticError(
        location,
        msg,
    )


@dataclass
class Statement:
    """A wrapper for clingo_funasp.ast.Statement that keeps track to the original statement for better error reporting during rewriting."""

    lib: Library
    original: ast.Statement
    rewritten: list[ast.Statement] = field(init=False)

    def __post_init__(self) -> None:
        self.rewritten = [self.original]

    def __str__(self) -> str:
        return ast_to_str(self.original)


def parse_string(library: core.Library, code: str) -> list[Statement]:
    """
    Parse a string into a list of AST statements.

    Args:
        library (Library): The library to use for parsing.
        code (str): The code string to parse.

    Returns:
        list[Statement]: The list of parsed statements.

    Raises:
        Raises ParsingError if parsing fails.
    """
    parsed: list[Statement] = []
    # The error messages are stored to restore them after parsing
    # The library is set to have no error messages during parsing
    # This avoids mixing errors from previous operations with parsing errors
    # This errors will be returned in the ParsingError if parsing fails
    saved_errors = library.error_messages
    library.error_messages = []
    try:
        ast.parse_string(
            library.library,
            code,
            lambda stmt: parsed.append(Statement(library.library, stmt)),
        )
    except RuntimeError as e:
        if str(e) != "parsing failed":  # pragma: no cover
            raise e
        raise ParsingException(
            [_process_error(library.library, error) for error in library.error_messages]
        )
    finally:
        library.error_messages = saved_errors
    return parsed


def parse_files(library: core.Library, files: Sequence[str]) -> list[Statement]:
    """
    Parse the given files into a list of AST statements.

    Args:
        library (Library): The library to use for parsing.
        files (Sequence[str]): The paths of the files to parse.

    Returns:
        list[Statement]: The list of parsed statements.

    Raises:
        Raises ParsingError if parsing fails.
    """
    parsed: list[Statement] = []
    # The error messages are stored to restore them after parsing
    # The library is set to have no error messages during parsing
    # This avoids mixing errors from previous operations with parsing errors
    # This errors will be returned in the ParsingError if parsing fails
    saved_errors = library.error_messages
    library.error_messages = []
    try:
        ast.parse_files(
            library.library,
            files,
            lambda stmt: parsed.append(Statement(library.library, stmt)),
        )
    except RuntimeError as e:
        if str(e) != "parsing failed":  # pragma: no cover
            raise e
        raise ParsingException(
            [_process_error(library.library, error) for error in library.error_messages]
        )
    finally:
        library.error_messages = saved_errors
    return parsed


def transform_iterable[T, R](
    library: Library, iterable: Iterable[T], fun: Callable[[Library, T], R | None]
) -> list[T | R] | None:
    """
    Apply a function to each element of an iterable.
    If all elements are transformed to None, return None. Otherwise, return an iterable of the transformed elements, where elements that were transformed to None are replaced by the original element.

    Args:
        iterable (Iterable[T]): The input iterable of elements of type T.
        fun (Callable[[Library, T], R | None]): A function that takes a Library and an element of type T and returns a transformed element of type R or None.

    Returns:
        list[T | R] | None: A list of transformed elements, or None if all elements were transformed to None.
    """
    result: list[T | R] = []
    all_none = True
    for element in iterable:
        new_element = fun(library, element)
        if new_element is not None:
            all_none = False
            result.append(new_element)
        else:
            result.append(element)
    if all_none:
        return None
    return result


_RELATION_STR = {
    ast.Relation.Equal: "=",
    ast.Relation.NotEqual: "!=",
    ast.Relation.Less: "<",
    ast.Relation.LessEqual: "<=",
    ast.Relation.Greater: ">",
    ast.Relation.GreaterEqual: ">=",
}

_AGGREGATE_STR = {
    ast.AggregateFunction.Count: "#count",
    ast.AggregateFunction.Sum: "#sum",
    ast.AggregateFunction.Sump: "#sum+",
    ast.AggregateFunction.Min: "#min",
    ast.AggregateFunction.Max: "#max",
}


def _function_to_str(name: str, arguments_strings: list[str]) -> str:
    """Render a function term given its name and pooled argument strings."""
    if len(arguments_strings) == 1 and not arguments_strings[0]:
        return name
    return f"{name}({';'.join(arguments_strings)})"


def _assignment_atom_to_str(atom: ast.Term) -> str | None:
    """Render a parser-generated ``Ff(t…,v)`` atom as ``f(t…) := v``."""
    if not isinstance(atom, ast.TermFunction) or not atom.name.startswith(
        PARSER_PREFIX
    ):
        return None
    name = atom.name[len(PARSER_PREFIX) :]
    arguments_strings: list[str] = []
    values: list[str] = []
    for arguments_tuple in atom.pool:
        arguments = arguments_tuple.arguments
        assert len(arguments) >= 1
        values.append(str(arguments[-1]))
        arguments_strings.append(",".join(str(a) for a in arguments[:-1]))
    if any(value != values[0] for value in values):
        # Pool entries with differing values cannot come from source.
        return None
    return f"{_function_to_str(name, arguments_strings)} := {values[0]}"


def _condition_to_str(condition: Sequence[ast.Literal]) -> str:
    """Render an element condition, with a leading separator when non-empty."""
    if not condition:
        return ""
    return ": " + ", ".join(str(literal) for literal in condition)


def _guards_to_str(
    left: ast.LeftGuard | None, inner: str, right: ast.RightGuard | None
) -> str:
    """Render a guarded aggregate given the rendered inner part."""
    parts = []
    if left is not None:
        parts.append(f"{left.term} {_RELATION_STR[left.relation]} ")
    parts.append(inner)
    if right is not None:
        parts.append(f" {_RELATION_STR[right.relation]} {right.term}")
    return "".join(parts)


def _set_aggregate_to_str(head: ast.HeadSetAggregate) -> str | None:
    """Render a choice with assignment elements as ``{ f(t) := v: cond; … }``."""
    elements = []
    has_assignment = False
    for element in head.elements:
        literal = element.literal
        assignment = (
            _assignment_atom_to_str(literal.atom)
            if isinstance(literal, ast.LiteralSymbolic)
            else None
        )
        if assignment is not None:
            has_assignment = True
        elements.append(
            f"{assignment or str(literal)}{_condition_to_str(element.condition)}"
        )
    if not has_assignment:
        return None
    inner = f"{{ {'; '.join(elements)} }}"
    return _guards_to_str(head.left, inner, head.right)


def _assignment_aggregate_to_str(
    head: ast.HeadAggregate, left_term: ast.TermFunction
) -> str:
    """Render an aggregate assignment head as ``f(t) := #agg{…}``."""
    name = left_term.name
    if name.startswith(PARSER_SOME_PREFIX):
        name = name[len(PARSER_SOME_PREFIX) :]
        aggregate = "#some"
    else:
        name = name[len(PARSER_PREFIX) :]
        aggregate = _AGGREGATE_STR[head.function]
    pool = [",".join(str(a) for a in t.arguments) for t in left_term.pool]
    elements = [
        ",".join(str(term) for term in element.tuple)
        + _condition_to_str(element.condition)
        for element in head.elements
    ]
    function = _function_to_str(name, pool)
    return f"{function} := {aggregate}{{{'; '.join(elements)}}}"


def _head_aggregate_to_str(head: ast.HeadAggregate) -> str | None:
    """Render a head aggregate, restoring assignments in guards or elements."""
    left = head.left
    if (
        left is not None
        and isinstance(left.term, ast.TermFunction)
        and left.term.name.startswith(PARSER_PREFIX)
    ):
        assert left.relation == ast.Relation.Equal
        assert head.right is None
        return _assignment_aggregate_to_str(head, left.term)

    elements = []
    has_assignment = False
    for element in head.elements:
        literal = element.literal
        assignment = (
            _assignment_atom_to_str(literal.atom)
            if isinstance(literal, ast.LiteralSymbolic)
            else None
        )
        if assignment is not None:
            has_assignment = True
        tuple_string = ",".join(str(term) for term in element.tuple)
        elements.append(
            f"{tuple_string}: {assignment or str(literal)}"
            f"{_condition_to_str(element.condition)}"
        )
    if not has_assignment:
        return None
    inner = f"{_AGGREGATE_STR[head.function]}{{ {'; '.join(elements)} }}"
    return _guards_to_str(head.left, inner, head.right)


def _head_to_str(head: ast.HeadLiteral) -> str | None:
    """Render a rule head in FASP syntax, or None if it has no F-encoding."""
    if isinstance(head, ast.HeadSimpleLiteral):
        literal = head.literal
        if not isinstance(literal, ast.LiteralSymbolic):
            return None
        return _assignment_atom_to_str(literal.atom)
    if isinstance(head, ast.HeadSetAggregate):
        return _set_aggregate_to_str(head)
    if isinstance(head, ast.HeadAggregate):
        return _head_aggregate_to_str(head)
    return None


def ast_to_str(statement: ast.Statement) -> str:
    """
    Render an as-parsed statement in FASP syntax.

    Parser-generated assignment encodings (``Ff(t,v)`` heads, ``Ff``/``FSf``
    head-aggregate guards, ``#show Ff/(n+1).`` signatures) are printed back
    in ``:=``/``#showf`` syntax; all other statements are printed as-is.
    """
    if isinstance(statement, ast.StatementShowSignature):
        if statement.name.startswith(PARSER_PREFIX):
            name = statement.name[len(PARSER_PREFIX) :]
            return f"#showf {name}/{statement.arity - 1}."
        return str(statement)
    if not isinstance(statement, ast.StatementRule):
        return str(statement)
    head = _head_to_str(statement.head)
    if head is None:
        return str(statement)
    body = ""
    if statement.body:
        body = " :- " + "; ".join(str(literal) for literal in statement.body)
    return f"{head}{body}."
