name: Deploy to PyPI

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "The build number."
        required: true
        type: string
        default: auto
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  # test:
  #   uses: ./.github/workflows/test.yml

  deploy:
    name: deploy
    # needs: test
    permissions:
      id-token: write
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Get build number and hash
        shell: bash -l {0}
        run: |
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.run_number = ${{ github.run_number }}"
          echo "inputs.build_number = ${{ inputs.build_number }}"
          echo "or ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || inputs.build_number == 'auto' }}"
          if [ "${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || inputs.build_number == 'auto' }}" ]; then
            echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
          else
            echo "BUILD_NUMBER=${{ inputs.build_number }}" >> $GITHUB_ENV
          fi
          echo "GIT_HASH=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "BUILD_NUMBER = $BUILD_NUMBER"
          echo "GIT_HASH = $GIT_HASH"
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Adjust version
        shell: bash -l {0}
        run: |
          pip install toml
          python .github/adjust_version.py --build-number ${BUILD_NUMBER} --git-hash ${GIT_HASH}

      # - name: install build dependencies
      #   run: python3 -m pip install build

      # - name: build package
      #   run: python3 -m build --sdist --wheel --outdir dist/

      # - name: upload package
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: package
      #     path: dist/
      # - name: publish package (pypi)
      #   if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
      #   uses: pypa/gh-action-pypi-publish@release/v1

      # - name: publish package (test.pypi)
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: "https://test.pypi.org/legacy/"