name: Run CI tests

on:
  - push
  - pull_request

env:
  FORCE_COLOR: "3"

jobs:
  build:
    name: fasp on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        # os: ['ubuntu-latest']
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge, potassco/label/dev-20
        # use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
        auto-update-conda: true
        activate-environment: clingo6
        auto-activate-base: false
        environment-file: envs/clingo6.yaml

    - name: run tests
      run: nox
