name: Run CI tests

on:
  pull_request:
  workflow_call:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'


env:
  FORCE_COLOR: "3"

jobs:
  build:
    name: fasp on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.13"]
        runAll:
          - ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')) }}
        exclude:
          - os: 'windows-latest'
            runAll: false
          - os: 'macos-latest'
            runAll: false

    steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: "checkout repository"
      uses: actions/checkout@v3

    - name: Pip install packages
      shell: bash -l {0}
      run: |
        pip install -r envs/requirements.txt
        pip install -e .

    - name: run application
      shell: bash -l {0}
      run: |
        python funasp examples/family.lp || if [ $? -eq 10 ]; then echo "Handled exit code 10"; else exit $?; fi

    - name: run tests
      run: nox
